import { pool } from "./db.js";

const createSchemaSql = `
CREATE TABLE IF NOT EXISTS pessoas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(20),
  cpf VARCHAR(14),
  perfil VARCHAR(20),
  data_ingresso DATE,
  data_nascimento DATE,
  nome_responsavel VARCHAR(255),
  telefone_responsavel VARCHAR(20),
  usa_medicamento VARCHAR(10),
  info_medicamentos TEXT,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT chk_pessoas_perfil CHECK (perfil IS NULL OR perfil IN ('aluno', 'professor')),
  CONSTRAINT chk_pessoas_status CHECK (status IN ('ativo', 'inativo')),
  CONSTRAINT chk_pessoas_medicamento CHECK (usa_medicamento IS NULL OR usa_medicamento IN ('sim', 'nao', 'não'))
);

CREATE TABLE IF NOT EXISTS empresas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_fantasia VARCHAR(255),
  razao_social VARCHAR(255) NOT NULL,
  cnpj VARCHAR(18) NOT NULL,
  endereco VARCHAR(500),
  telefone VARCHAR(20),
  nome_responsavel_rh VARCHAR(255),
  telefone_responsavel_rh VARCHAR(20),
  email_responsavel_rh VARCHAR(255),
  status VARCHAR(20) NOT NULL,
  CONSTRAINT chk_empresas_status CHECK (status IN ('ativo', 'inativo'))
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  token_recuperacao VARCHAR(255),
  validade_token TIMESTAMP,
  nivel_acesso VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS funcoes_cargos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo_funcao VARCHAR(150) NOT NULL,
  departamento VARCHAR(100),
  nivel VARCHAR(50),
  descricao TEXT,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT chk_funcoes_status CHECK (status IN ('ativo', 'inativo'))
);

CREATE TABLE IF NOT EXISTS itens_avaliacao (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itens VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT chk_itens_status CHECK (status IN ('ativo', 'inativo'))
);

CREATE TABLE IF NOT EXISTS questionarios_modelo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(80) NOT NULL UNIQUE,
  questoes JSONB NOT NULL DEFAULT '[]'::jsonb,
  atualizado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS avaliacoes_experiencia (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(80) NOT NULL,
  nome VARCHAR(255),
  form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  questoes JSONB NOT NULL DEFAULT '[]'::jsonb,
  criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS listas_encaminhados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano_referencia VARCHAR(10) NOT NULL,
  data_encaminhamento DATE,
  usuarios JSONB NOT NULL DEFAULT '[]'::jsonb,
  criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ficha_avaliacao_aluno_professor (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_avaliacao VARCHAR(100) NOT NULL,
  id_pessoa_aluno INTEGER NOT NULL,
  data_entrada DATE,
  data_avaliacao DATE NOT NULL,
  id_pessoa_professor INTEGER NOT NULL,
  CONSTRAINT fk_ficha_aval_aluno FOREIGN KEY (id_pessoa_aluno) REFERENCES pessoas(id),
  CONSTRAINT fk_ficha_aval_prof FOREIGN KEY (id_pessoa_professor) REFERENCES pessoas(id)
);

CREATE TABLE IF NOT EXISTS ficha_avaliacao_questionario (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_item INTEGER NOT NULL,
  id_ficha_avaliacao_aluno_prof INTEGER NOT NULL,
  resultado VARCHAR(100),
  campo_pergunta1 TEXT,
  campo_pergunta2 TEXT,
  CONSTRAINT fk_questionario_item FOREIGN KEY (id_item) REFERENCES itens_avaliacao(id),
  CONSTRAINT fk_questionario_ficha FOREIGN KEY (id_ficha_avaliacao_aluno_prof) REFERENCES ficha_avaliacao_aluno_professor(id)
);

CREATE TABLE IF NOT EXISTS ficha_acompanhamento (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pessoa_aluno INTEGER NOT NULL,
  data_admissao DATE,
  data_visita DATE NOT NULL,
  id_empresa INTEGER NOT NULL,
  parecer_geral TEXT,
  CONSTRAINT fk_acomp_pessoa FOREIGN KEY (id_pessoa_aluno) REFERENCES pessoas(id),
  CONSTRAINT fk_acomp_empresa FOREIGN KEY (id_empresa) REFERENCES empresas(id)
);

CREATE TABLE IF NOT EXISTS controle_interno_avaliacao_usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pessoa_aluno INTEGER NOT NULL,
  data_entrada DATE,
  dt_1_avaliacao DATE,
  dt_2_avaliacao DATE,
  dt_1_entrevista_pais DATE,
  dt_2_entrevista_pais DATE,
  resultado VARCHAR(255),
  CONSTRAINT fk_controle_pessoa FOREIGN KEY (id_pessoa_aluno) REFERENCES pessoas(id)
);


`;

export const ensureDatabaseSchema = async () => {
  await pool.query(createSchemaSql);

  // Compatibilidade para bancos ja existentes antes da coluna de telefone do contato RH.
  await pool.query(
    "ALTER TABLE IF EXISTS empresas ADD COLUMN IF NOT EXISTS telefone_responsavel_rh VARCHAR(20)"
  );

  await pool.query(
    "ALTER TABLE IF EXISTS listas_encaminhados ADD COLUMN IF NOT EXISTS data_encaminhamento DATE"
  );

  await pool.query(
    "ALTER TABLE IF EXISTS lista_encaminhados ADD COLUMN IF NOT EXISTS status_encaminhamento VARCHAR(20) NOT NULL DEFAULT 'ativo'"
  );

  await pool.query(
    "ALTER TABLE IF EXISTS lista_encaminhados DROP CONSTRAINT IF EXISTS chk_encaminhados_status"
  );

  await pool.query(
    "ALTER TABLE IF EXISTS lista_encaminhados ADD CONSTRAINT chk_encaminhados_status CHECK (status_encaminhamento IN ('ativo', 'inativo'))"
  );
};
